version: "3"

vars:
  DOCKER_IMAGE: adrianliechti/loop-registry

tasks:
  push:
    cmds:
      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}} .
  install:
    cmds:
      - kubectl create ns loop -o yaml --dry-run=client | kubectl apply -f -
      - kubectl apply -f kubernetes/*

  uninstall:
    cmds:
      - kubectl delete -f kubernetes/*
