apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: platform
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: adrianliechti/loop-registry
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry
          resources: {}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: platform
  labels:
    app: registry
spec:
  type: ClusterIP
  selector:
    app: registry
  ports:
    - name: http
      port: 80
      targetPort: 5000
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry
  namespace: platform
  labels:
    app: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
